version: 2
deployment:
  prod:
    branch: master
    heroku:
      appname: wt-codingtask

jobs:
  build:
    docker:
      - image: circleci/node:7.10
      - image: mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: npm run unit